export const modules = [
  {
    name: "Iniciante",
    exerciseRequirements: { 3: 2, 5: 4, 7: 6 },
    chapters: [
      {
        number: 1, title: "Visão Geral",
        lessons: [
          { id: "cap01_aula01", chapter: 1, lessonNumber: 1, title: "Bem-vindo!", youtubeId: "WiGU_ZB-u0w" },
          { id: "cap01_aula02", chapter: 1, lessonNumber: 2, title: "Por que Go?", youtubeId: "jXA0O5b-F1g" },
          { id: "cap01_aula03", chapter: 1, lessonNumber: 3, title: "Sucesso", youtubeId: "CvH9fC2eYO8" },
          { id: "cap01_aula04", chapter: 1, lessonNumber: 4, title: "Recursos", youtubeId: "n7PZo55Wl5A" },
          { id: "cap01_aula05", chapter: 1, lessonNumber: 5, title: "Como esse curso funciona", youtubeId: "V9zfX8Yhc9g" },
          { id: "cap01_aula06", chapter: 1, lessonNumber: 6, title: "Update: Exercícios", youtubeId: "B5sy5v2dT9Y" },
        ],
      },
      {
        number: 2, title: "Variáveis, Valores & Tipos",
        lessons: [
          { id: "cap02_aula01", chapter: 2, lessonNumber: 1, title: "Go Playground", youtubeId: "Qf2645sTqH0" },
          { id: "cap02_aula02", chapter: 2, lessonNumber: 2, title: "Hello world!", youtubeId: "tdZ2I2RZ7JI" },
          { id: "cap02_aula03", chapter: 2, lessonNumber: 3, title: "Operador curto de declaração", youtubeId: "QT7YvrEWMGE" },
          { id: "cap02_aula04", chapter: 2, lessonNumber: 4, title: "A palavra-chave var", youtubeId: "YAGKHSNWdEE" },
          { id: "cap02_aula05", chapter: 2, lessonNumber: 5, title: "Explorando tipos", youtubeId: "DazALie4u5E" },
          { id: "cap02_aula06", chapter: 2, lessonNumber: 6, title: "Valor zero", youtubeId: "Ruwp2xLD_AI" },
          { id: "cap02_aula07", chapter: 2, lessonNumber: 7, title: "O pacote fmt", youtubeId: "IjDiONSi-tI" },
          { id: "cap02_aula08", chapter: 2, lessonNumber: 8, title: "Criando seu próprio tipo", youtubeId: "DGHYibXY6Qk" },
          { id: "cap02_aula09", chapter: 2, lessonNumber: 9, title: "Conversão, não coerção", youtubeId: "s0UYWJUz30k" },
        ],
      },
      {
        number: 3, title: "Exercícios: Nível #1", isExercise: true, requiredBy: 2,
        lessons: [
          { id: "cap03_aula01", chapter: 3, lessonNumber: 1, title: "Exercício 1", youtubeId: "5K17jFDXvWw", isExercise: true },
          { id: "cap03_aula02", chapter: 3, lessonNumber: 2, title: "Exercício 2", youtubeId: "Q7ZrIDMj9zc", isExercise: true },
          { id: "cap03_aula03", chapter: 3, lessonNumber: 3, title: "Exercício 3", youtubeId: "VkuZ4QMnoZM", isExercise: true },
          { id: "cap03_aula04", chapter: 3, lessonNumber: 4, title: "Exercício 4", youtubeId: "5-0S-gefNe0", isExercise: true },
          { id: "cap03_aula05", chapter: 3, lessonNumber: 5, title: "Exercício 5", youtubeId: "O0r318FN_Uw", isExercise: true },
          { id: "cap03_aula06", chapter: 3, lessonNumber: 6, title: "Exercício 6", youtubeId: "OINd35-02xo", isExercise: true },
        ],
      },
      {
        number: 4, title: "Fundamentos da Programação",
        lessons: [
          { id: "cap04_aula01", chapter: 4, lessonNumber: 1, title: "Tipo booleano", youtubeId: "voisg61hPXA" },
          { id: "cap04_aula02", chapter: 4, lessonNumber: 2, title: "Como os computadores funcionam", youtubeId: "C55_dhNmvrQ" },
          { id: "cap04_aula03", chapter: 4, lessonNumber: 3, title: "Tipos numéricos", youtubeId: "3yIKCLSWAHA" },
          { id: "cap04_aula04", chapter: 4, lessonNumber: 4, title: "Overflow", youtubeId: "g0j0XaVk2EI" },
          { id: "cap04_aula05", chapter: 4, lessonNumber: 5, title: "Tipo string", youtubeId: "AcyS0_BAy7U" },
          { id: "cap04_aula06", chapter: 4, lessonNumber: 6, title: "Sistemas numéricos", youtubeId: "Ma3M7Pdd7HI" },
          { id: "cap04_aula07", chapter: 4, lessonNumber: 7, title: "Constantes", youtubeId: "Yaw80pKukMc" },
          { id: "cap04_aula08", chapter: 4, lessonNumber: 8, title: "Iota", youtubeId: "1IduyaGMO3g" },
          { id: "cap04_aula09", chapter: 4, lessonNumber: 9, title: "Deslocamento de bits", youtubeId: "USntMXkOihY" },
        ],
      },
      {
        number: 5, title: "Exercícios: Nível #2", isExercise: true, requiredBy: 4,
        lessons: [
          { id: "cap05_aula01", chapter: 5, lessonNumber: 1, title: "Exercício 1", youtubeId: "onK_nd--g1g", isExercise: true },
          { id: "cap05_aula02", chapter: 5, lessonNumber: 2, title: "Exercício 2", youtubeId: "8zEZw19gRTo", isExercise: true },
          { id: "cap05_aula03", chapter: 5, lessonNumber: 3, title: "Exercício 3", youtubeId: "12o81rTFu_w", isExercise: true },
          { id: "cap05_aula04", chapter: 5, lessonNumber: 4, title: "Exercício 4", youtubeId: "NxntmGW62Ag", isExercise: true },
          { id: "cap05_aula05", chapter: 5, lessonNumber: 5, title: "Exercício 5", youtubeId: "LSKCaxazLGs", isExercise: true },
          { id: "cap05_aula06", chapter: 5, lessonNumber: 6, title: "Exercício 6", youtubeId: "M07eDn7FyxI", isExercise: true },
          { id: "cap05_aula07", chapter: 5, lessonNumber: 7, title: "Exercício 7", youtubeId: "9eMbGsKcWlc", isExercise: true },
        ],
      },
      {
        number: 6, title: "Fluxo de Controle",
        lessons: [
          { id: "cap06_aula01", chapter: 6, lessonNumber: 1, title: "Entendendo fluxo de controle", youtubeId: "1G-tbQ6UE_A" },
          { id: "cap06_aula02", chapter: 6, lessonNumber: 2, title: "Loops: inicialização, condição, pós", youtubeId: "g_Qdxi1b2cE" },
          { id: "cap06_aula03", chapter: 6, lessonNumber: 3, title: "Loops: nested loop", youtubeId: "EL9wo6Zrz9o" },
          { id: "cap06_aula04", chapter: 6, lessonNumber: 4, title: "Loops: a declaração for", youtubeId: "QDaiqhTq3TA" },
          { id: "cap06_aula05", chapter: 6, lessonNumber: 5, title: "Loops: break & continue", youtubeId: "eGdB8FMCZ0s" },
          { id: "cap06_aula06", chapter: 6, lessonNumber: 6, title: "Loops: utilizando ascii", youtubeId: "hu0qcmbhH8s" },
          { id: "cap06_aula07", chapter: 6, lessonNumber: 7, title: "Condicionais: a declaração if", youtubeId: "LBlrrV0iRKg" },
          { id: "cap06_aula08", chapter: 6, lessonNumber: 8, title: "Condicionais: if, else if, else", youtubeId: "ZfCgoVaxMGE" },
          { id: "cap06_aula09", chapter: 6, lessonNumber: 9, title: "Condicionais: a declaração switch", youtubeId: "WFFidtqPfhk" },
          { id: "cap06_aula10", chapter: 6, lessonNumber: 10, title: "Condicionais: switch pt. 2 & documentação", youtubeId: "v6HnDiPyynA" },
          { id: "cap06_aula11", chapter: 6, lessonNumber: 11, title: "Operadores lógicos condicionais", youtubeId: "Y5HamAGQzUg" },
        ],
      },
      {
        number: 7, title: "Exercícios: Nível #3", isExercise: true, requiredBy: 6,
        lessons: [
          { id: "cap07_aula01", chapter: 7, lessonNumber: 1, title: "Exercício 1", youtubeId: "xXUTHJzJNgM", isExercise: true },
          { id: "cap07_aula02", chapter: 7, lessonNumber: 2, title: "Exercício 2", youtubeId: "w_JW1bWT08s", isExercise: true },
          { id: "cap07_aula03", chapter: 7, lessonNumber: 3, title: "Exercício 3", youtubeId: "2y7qV_9SsiI", isExercise: true },
          { id: "cap07_aula04", chapter: 7, lessonNumber: 4, title: "Exercício 4", youtubeId: "bWvpNLBSEKk", isExercise: true },
          { id: "cap07_aula05", chapter: 7, lessonNumber: 5, title: "Exercício 5", youtubeId: "pIVF9vf2wAc", isExercise: true },
          { id: "cap07_aula06", chapter: 7, lessonNumber: 6, title: "Exercício 6", youtubeId: "VsDnqhpFVZI", isExercise: true },
          { id: "cap07_aula07", chapter: 7, lessonNumber: 7, title: "Exercício 7", youtubeId: "haYnFVssUr4", isExercise: true },
          { id: "cap07_aula08", chapter: 7, lessonNumber: 8, title: "Exercício 8", youtubeId: "mm3JM2ZG0us", isExercise: true },
          { id: "cap07_aula09", chapter: 7, lessonNumber: 9, title: "Exercício 9", youtubeId: "XxQQOHHQCwY", isExercise: true },
          { id: "cap07_aula10", chapter: 7, lessonNumber: 10, title: "Exercício 10", youtubeId: "3DP6lzRLkdw", isExercise: true },
        ],
      },
    ],
  },
  {
    name: "Intermediário",
    exerciseRequirements: { 9: 8, 11: 10, 13: 12, 15: 14, 17: 16 },
    chapters: [
      {
        number: 8, title: "Agrupamentos de Dados",
        lessons: [
          { id: "cap08_aula01", chapter: 8, lessonNumber: 1, title: "Array", youtubeId: "i_3O4ooSVCM" },
          { id: "cap08_aula02", chapter: 8, lessonNumber: 2, title: "Slice: literal composta", youtubeId: "MMzTlWZ9Gjw" },
          { id: "cap08_aula03", chapter: 8, lessonNumber: 3, title: "Slice: for range", youtubeId: "l6O8HWaoy_w" },
          { id: "cap08_aula04", chapter: 8, lessonNumber: 4, title: "Slice: fatiando ou deletando", youtubeId: "G0rxcnojV_U" },
          { id: "cap08_aula05", chapter: 8, lessonNumber: 5, title: "Slice: anexando a uma slice", youtubeId: "MbvABKiAABA" },
          { id: "cap08_aula06", chapter: 8, lessonNumber: 6, title: "Slice: make", youtubeId: "IMO5_ancK9w" },
          { id: "cap08_aula07", chapter: 8, lessonNumber: 7, title: "Slice: slice multi-dimensional", youtubeId: "o3yoYGWqrDE" },
          { id: "cap08_aula08", chapter: 8, lessonNumber: 8, title: "Slice: a surpresa do array subjacente", youtubeId: "dRNNC7VpztE" },
          { id: "cap08_aula09", chapter: 8, lessonNumber: 9, title: "Maps: introdução", youtubeId: "clobcQqAgos" },
          { id: "cap08_aula10", chapter: 8, lessonNumber: 10, title: "Maps: range & deletando", youtubeId: "7a6I-GnqtSE" },
        ],
      },
      {
        number: 9, title: "Exercícios: Nível #4", isExercise: true, requiredBy: 8,
        lessons: [
          { id: "cap09_aula01", chapter: 9, lessonNumber: 1, title: "Exercício 1", youtubeId: "cjUFrS3hqgU", isExercise: true },
          { id: "cap09_aula02", chapter: 9, lessonNumber: 2, title: "Exercício 2", youtubeId: "xpeExQ5C5S8", isExercise: true },
          { id: "cap09_aula03", chapter: 9, lessonNumber: 3, title: "Exercício 3", youtubeId: "Wzc5VOjh-XQ", isExercise: true },
          { id: "cap09_aula04", chapter: 9, lessonNumber: 4, title: "Exercício 4", youtubeId: "8Lym_4_dwOQ", isExercise: true },
          { id: "cap09_aula05", chapter: 9, lessonNumber: 5, title: "Exercício 5", youtubeId: "gA1cTnWjPaU", isExercise: true },
          { id: "cap09_aula06", chapter: 9, lessonNumber: 6, title: "Exercício 6", youtubeId: "KOhQCm8f8AE", isExercise: true },
          { id: "cap09_aula07", chapter: 9, lessonNumber: 7, title: "Exercício 7", youtubeId: "f4lvrtXsGIM", isExercise: true },
          { id: "cap09_aula08", chapter: 9, lessonNumber: 8, title: "Exercício 8", youtubeId: "rfQkR1bH3qw", isExercise: true },
          { id: "cap09_aula09", chapter: 9, lessonNumber: 9, title: "Exercício 9", youtubeId: "AKPdowl7tsw", isExercise: true },
          { id: "cap09_aula10", chapter: 9, lessonNumber: 10, title: "Exercício 10", youtubeId: "2cx79-nwNQU", isExercise: true },
        ],
      },
      {
        number: 10, title: "Structs",
        lessons: [
          { id: "cap10_aula01", chapter: 10, lessonNumber: 1, title: "Struct", youtubeId: "EaOGcmXo4F8" },
          { id: "cap10_aula02", chapter: 10, lessonNumber: 2, title: "Structs embutidos", youtubeId: "KBFprVi_haM" },
          { id: "cap10_aula03", chapter: 10, lessonNumber: 3, title: "Lendo a documentação", youtubeId: "dKaElWlGKo0" },
          { id: "cap10_aula04", chapter: 10, lessonNumber: 4, title: "Structs anônimos", youtubeId: "Y4MKS3gJQ9Q" },
        ],
      },
      {
        number: 11, title: "Exercícios: Nível #5", isExercise: true, requiredBy: 10,
        lessons: [
          { id: "cap11_aula01", chapter: 11, lessonNumber: 1, title: "Exercício 1", youtubeId: "OQMOIcZ-ShY", isExercise: true },
          { id: "cap11_aula02", chapter: 11, lessonNumber: 2, title: "Exercício 2", youtubeId: "uDajGJbXP6A", isExercise: true },
          { id: "cap11_aula03", chapter: 11, lessonNumber: 3, title: "Exercício 3", youtubeId: "ji14zPQgmN8", isExercise: true },
          { id: "cap11_aula04", chapter: 11, lessonNumber: 4, title: "Exercício 4", youtubeId: "uNnLSuRqBuY", isExercise: true },
        ],
      },
      {
        number: 12, title: "Funções",
        lessons: [
          { id: "cap12_aula01", chapter: 12, lessonNumber: 1, title: "Sintaxe", youtubeId: "PPOBe49M8V0" },
          { id: "cap12_aula02", chapter: 12, lessonNumber: 2, title: "Desenrolando uma slice", youtubeId: "pV5OEqIRPh4" },
          { id: "cap12_aula03", chapter: 12, lessonNumber: 3, title: "Defer", youtubeId: "zxVqQ59YfSY" },
          { id: "cap12_aula04", chapter: 12, lessonNumber: 4, title: "Métodos", youtubeId: "YrCt7Wo2aAQ" },
          { id: "cap12_aula05", chapter: 12, lessonNumber: 5, title: "Interfaces & polimorfismo", youtubeId: "2zTENBJTlD0" },
          { id: "cap12_aula06", chapter: 12, lessonNumber: 6, title: "Funções anônimas", youtubeId: "pp8NKaoyefQ" },
          { id: "cap12_aula07", chapter: 12, lessonNumber: 7, title: "Func como expressão", youtubeId: "j9C66R4BMWM" },
          { id: "cap12_aula08", chapter: 12, lessonNumber: 8, title: "Retornando uma função", youtubeId: "9Oxmya_A-Sc" },
          { id: "cap12_aula09", chapter: 12, lessonNumber: 9, title: "Callback", youtubeId: "u8qBzOAhbRM" },
          { id: "cap12_aula10", chapter: 12, lessonNumber: 10, title: "Closure", youtubeId: "mOM0qTB5ppU" },
          { id: "cap12_aula11", chapter: 12, lessonNumber: 11, title: "Recursividade", youtubeId: "1-pop5h5RAs" },
        ],
      },
      {
        number: 13, title: "Exercícios: Nível #6", isExercise: true, requiredBy: 12,
        lessons: [
          { id: "cap13_aula01", chapter: 13, lessonNumber: 1, title: "Exercício 1", youtubeId: "Uuj3-PrTk-Q", isExercise: true },
          { id: "cap13_aula02", chapter: 13, lessonNumber: 2, title: "Exercício 2", youtubeId: "ZLOyRrhSydk", isExercise: true },
          { id: "cap13_aula03", chapter: 13, lessonNumber: 3, title: "Exercício 3", youtubeId: "EoaMCgbqKSI", isExercise: true },
          { id: "cap13_aula04", chapter: 13, lessonNumber: 4, title: "Exercício 4", youtubeId: "HxdO5sm3cRY", isExercise: true },
          { id: "cap13_aula05", chapter: 13, lessonNumber: 5, title: "Exercício 5", youtubeId: "3pbmLfcgN2s", isExercise: true },
          { id: "cap13_aula06", chapter: 13, lessonNumber: 6, title: "Exercício 6", youtubeId: "NAXWCqhJIEU", isExercise: true },
          { id: "cap13_aula07", chapter: 13, lessonNumber: 7, title: "Exercício 7", youtubeId: "ePh12R5jnIM", isExercise: true },
          { id: "cap13_aula08", chapter: 13, lessonNumber: 8, title: "Exercício 8", youtubeId: "JS5G5O4LOVI", isExercise: true },
          { id: "cap13_aula09", chapter: 13, lessonNumber: 9, title: "Exercício 9", youtubeId: "EXQknIy6NE0", isExercise: true },
          { id: "cap13_aula10", chapter: 13, lessonNumber: 10, title: "Exercício 10", youtubeId: "LDJF2ceCRDE", isExercise: true },
          { id: "cap13_aula11", chapter: 13, lessonNumber: 11, title: "Exercício 11", youtubeId: "cOOH6mKWNs8", isExercise: true },
        ],
      },
      {
        number: 14, title: "Ponteiros",
        lessons: [
          { id: "cap14_aula01", chapter: 14, lessonNumber: 1, title: "O que são ponteiros?", youtubeId: "l2YJ-5GpGr8" },
          { id: "cap14_aula02", chapter: 14, lessonNumber: 2, title: "Quando usar ponteiros", youtubeId: "0slBes2RYgc" },
        ],
      },
      {
        number: 15, title: "Exercícios: Nível #7", isExercise: true, requiredBy: 14,
        lessons: [
          { id: "cap15_aula01", chapter: 15, lessonNumber: 1, title: "Exercício 1", youtubeId: "lSAVf0RgmHc", isExercise: true },
          { id: "cap15_aula02", chapter: 15, lessonNumber: 2, title: "Exercício 2", youtubeId: "XVd-y0t5fno", isExercise: true },
        ],
      },
      {
        number: 16, title: "Aplicações",
        lessons: [
          { id: "cap16_aula01", chapter: 16, lessonNumber: 1, title: "Documentação JSON", youtubeId: "jnnIgvV0_yA" },
          { id: "cap16_aula02", chapter: 16, lessonNumber: 2, title: "JSON marshal", youtubeId: "-tU2PSY8F5w" },
          { id: "cap16_aula03", chapter: 16, lessonNumber: 3, title: "JSON unmarshal", youtubeId: "mcbj-wy8Ro8" },
          { id: "cap16_aula04", chapter: 16, lessonNumber: 4, title: "A interface Writer", youtubeId: "S4hEdA0RPVI" },
          { id: "cap16_aula05", chapter: 16, lessonNumber: 5, title: "O pacote sort", youtubeId: "b67JIGYM6Hc" },
          { id: "cap16_aula06", chapter: 16, lessonNumber: 6, title: "Customizando o sort", youtubeId: "0E-q22d3QD4" },
          { id: "cap16_aula07", chapter: 16, lessonNumber: 7, title: "bcrypt", youtubeId: "4vCb7jmwkzM" },
        ],
      },
      {
        number: 17, title: "Exercícios: Nível #8", isExercise: true, requiredBy: 16,
        lessons: [
          { id: "cap17_aula01", chapter: 17, lessonNumber: 1, title: "Exercício 1", youtubeId: "-wHOZpi697M", isExercise: true },
          { id: "cap17_aula02", chapter: 17, lessonNumber: 2, title: "Exercício 2", youtubeId: "oUsTxBwHaMM", isExercise: true },
          { id: "cap17_aula03", chapter: 17, lessonNumber: 3, title: "Exercício 3", youtubeId: "Y1Ym6Ai3uys", isExercise: true },
          { id: "cap17_aula04", chapter: 17, lessonNumber: 4, title: "Exercício 4", youtubeId: "fZZclCKnr7k", isExercise: true },
          { id: "cap17_aula05", chapter: 17, lessonNumber: 5, title: "Exercício 5", youtubeId: "3hidzcEZ0KE", isExercise: true },
        ],
      },
    ],
  },
  {
    name: "Avançado",
    exerciseRequirements: { 20: 18 },
    chapters: [
      {
        number: 18, title: "Concorrência",
        lessons: [
          { id: "cap18_aula01", chapter: 18, lessonNumber: 1, title: "Concorrência vs. paralelismo", youtubeId: "unofca9ooS4" },
          { id: "cap18_aula02", chapter: 18, lessonNumber: 2, title: "Goroutines & WaitGroups", youtubeId: "4jXSU2jw3Ag" },
          { id: "cap18_aula03", chapter: 18, lessonNumber: 3, title: "Discussão: Condição de corrida", youtubeId: "0qGILXmLfMM" },
          { id: "cap18_aula04", chapter: 18, lessonNumber: 4, title: "Na prática: Condição de corrida", youtubeId: "XxG7qqJzDKk" },
          { id: "cap18_aula05", chapter: 18, lessonNumber: 5, title: "Mutex", youtubeId: "egd4WHJMwC0" },
          { id: "cap18_aula06", chapter: 18, lessonNumber: 6, title: "Atomic", youtubeId: "iFlQ2yAYcp4" },
        ],
      },
      {
        number: 20, title: "Exercícios: Nível #9", isExercise: true, requiredBy: 18,
        lessons: [
          { id: "cap20_aula01", chapter: 20, lessonNumber: 1, title: "Exercício 1", youtubeId: "Y9QEvz4D_9E", isExercise: true },
          { id: "cap20_aula02", chapter: 20, lessonNumber: 2, title: "Exercício 2", youtubeId: "iu632z7i3MM", isExercise: true },
          { id: "cap20_aula03", chapter: 20, lessonNumber: 3, title: "Exercício 3", youtubeId: "cCWvFijhObU", isExercise: true },
          { id: "cap20_aula04", chapter: 20, lessonNumber: 4, title: "Exercício 4", youtubeId: "q_tHbwD0n6w", isExercise: true },
          { id: "cap20_aula05", chapter: 20, lessonNumber: 5, title: "Exercício 5", youtubeId: "58_JeZA3V_0", isExercise: true },
          { id: "cap20_aula06", chapter: 20, lessonNumber: 6, title: "Exercício 6", youtubeId: "weEJtEyl79o", isExercise: true },
          { id: "cap20_aula07", chapter: 20, lessonNumber: 7, title: "Exercício 7", youtubeId: "t0jraJONVzs", isExercise: true },
        ],
      },
      {
        number: 21, title: "Canais",
        lessons: [
          { id: "cap21_aula01", chapter: 21, lessonNumber: 1, title: "Entendendo canais", youtubeId: "jF0xuhnPkDg" },
          { id: "cap21_aula02", chapter: 21, lessonNumber: 2, title: "Canais direcionais & Utilizando canais", youtubeId: "vYYHoKLb_8I" },
          { id: "cap21_aula03", chapter: 21, lessonNumber: 3, title: "Range e close", youtubeId: "B1UArMoYDJ0" },
          { id: "cap21_aula04", chapter: 21, lessonNumber: 4, title: "Select", youtubeId: "dp8s5jAc7h0" },
          { id: "cap21_aula05", chapter: 21, lessonNumber: 5, title: "A expressão comma ok", youtubeId: "wWQ0BbbQ-28" },
          { id: "cap21_aula06", chapter: 21, lessonNumber: 6, title: "Convergência", youtubeId: "VJyryKEMleU" },
          { id: "cap21_aula07", chapter: 21, lessonNumber: 7, title: "Divergência", youtubeId: "8X6eOnSJu5g" },
          { id: "cap21_aula08", chapter: 21, lessonNumber: 8, title: "Context", youtubeId: "PhTtrrsUH8c" },
        ],
      },
    ],
  },
  {
    name: "Ecossistema",
    exerciseRequirements: {},
    chapters: [
      {
        number: 19, title: "Ambiente de Desenvolvimento",
        lessons: [
          { id: "cap19_aula01", chapter: 19, lessonNumber: 1, title: "O terminal", youtubeId: "CgrYtlaOgCg" },
          { id: "cap19_aula02", chapter: 19, lessonNumber: 2, title: "Go Workspace", youtubeId: "geLSoE5D0xA" },
          { id: "cap19_aula03", chapter: 19, lessonNumber: 3, title: "IDEs", youtubeId: "1E3KMnYnqCk" },
          { id: "cap19_aula04", chapter: 19, lessonNumber: 4, title: "Comandos Go", youtubeId: "kJNq487dt7w" },
          { id: "cap19_aula05", chapter: 19, lessonNumber: 5, title: "Repositórios no GitHub", youtubeId: "XQUMNuGyVa4" },
          { id: "cap19_aula06", chapter: 19, lessonNumber: 6, title: "Explorando o GitHub", youtubeId: "t-S2s1K3b5Q" },
          { id: "cap19_aula07", chapter: 19, lessonNumber: 7, title: "Compilação cruzada", youtubeId: "k0pV_JoiZbI" },
          { id: "cap19_aula08", chapter: 19, lessonNumber: 8, title: "Pacotes", youtubeId: "SO-RFPSqD3c" },
        ],
      },
    ],
  },
];
